//
//  HomeCardsetCell.swift
//  Caiva_iOS
//
//  Created by Shutaro Aoyama on 2018/07/05.
//  Copyright © 2018年 Bluemountain. All rights reserved.
//

import UIKit
import MGSwipeTableCell

class HomeCardsetCell: MGSwipeTableCell {
    
    @IBOutlet weak var boxView: GradientView!
    @IBOutlet weak var name: UILabel!
    @IBOutlet weak var amount: UILabel!
    @IBOutlet weak var perc: UILabel!
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
//
//    func setSmartCardset() {
//        boxView.topColor = UIColor(hexString: "714296")!
//        boxView.bottomColor = UIColor(hexString: "AE4F90")!
//        boxView.shadowColor = UIColor(hexString: "000000", alpha: 0.2)!
//        
//        name.textColor = UIColor.white
//        amount.textColor = UIColor.white
//        perc.textColor = UIColor.white
//
//        name.text = "Smart Mixture"
//        amount.text = "Cardset generated by AI"
//        perc.text = "AI"
//    }
    
    func setText(nameData: String, amountData: Int, percData: Double) {
        name.text = nameData
        amount.text = String(amountData) + " Cards"
        guard percData > 1 else {
            perc.text = String(Int(percData * 100)) + "%"
            return
        }
    }
}
